### ISSUE TITLE
关于jobName设置无效，jobParameter拿不到

### ISSUE THREAD

**Issue by JunliXia** [kuhn-he/elastic-job-lite-spring-boot-starter#1]
设置ElasticSimpleJob后，发现jobName与jobParameter非设置值。
原代码为：
SimpleJobConfiguration simpleJobConfiguration=new SimpleJobConfiguration(JobCoreConfiguration.newBuilder(simpleJob.getClass().getName(), cron, elasticSimpleJobAnnotation.shardingTotalCount()).shardingItemParameters(elasticSimpleJobAnnotation.shardingItemParameters()).build(), simpleJob.getClass().getCanonicalName());

若更改为以下代码则可解决问题：
SimpleJobConfiguration simpleJobConfiguration=new SimpleJobConfiguration(JobCoreConfiguration.newBuilder(elasticSimpleJobAnnotation.jobName(), cron, elasticSimpleJobAnnotation.shardingTotalCount()).shardingItemParameters(elasticSimpleJobAnnotation.shardingItemParameters()).jobParameter(elasticSimpleJobAnnotation.jobParameter()).build(), simpleJob.getClass().getCanonicalName());

**Comment by kuhn-he** [comment]
谢谢，后续我们会改进




--
发自我的网易邮箱手机智能版



在 2018-06-13 18:18:49，JunliXia <notifications@github.com> 写道：


设置ElasticSimpleJob后，发现jobName与jobParameter非设置值。
原代码为：
SimpleJobConfiguration simpleJobConfiguration=new SimpleJobConfiguration(JobCoreConfiguration.newBuilder(simpleJob.getClass().getName(), cron, elasticSimpleJobAnnotation.shardingTotalCount()).shardingItemParameters(elasticSimpleJobAnnotation.shardingItemParameters()).build(), simpleJob.getClass().getCanonicalName());

若更改为以下代码则可解决问题：
SimpleJobConfiguration simpleJobConfiguration=new SimpleJobConfiguration(JobCoreConfiguration.newBuilder(elasticSimpleJobAnnotation.jobName(), cron, elasticSimpleJobAnnotation.shardingTotalCount()).shardingItemParameters(elasticSimpleJobAnnotation.shardingItemParameters()).jobParameter(elasticSimpleJobAnnotation.jobParameter()).build(), simpleJob.getClass().getCanonicalName());
