### ISSUE TITLE
能不能支持一下表达式，这样可配置

### ISSUE THREAD

**Issue by say1or** [kuhn-he/elastic-job-lite-spring-boot-starter#4]
![image](https://user-images.githubusercontent.com/19355699/50670960-c3f6eb00-1009-11e9-8c91-f80d3900b062.png)

**Comment by say1or** [comment]
![image](https://user-images.githubusercontent.com/19355699/50670974-dc670580-1009-11e9-8734-025cb42caac6.png)

**Comment by kuhn-he** [comment]
目前不支持，后续会考虑引入
